"use client";

import Link from "next/link";
import type { CSSProperties } from "react";
import AnimatedIcon from "@/components/ui/AnimatedIcon";

type FeatureIcon = "calendar" | "dumbbell" | "utensils" | "calculator" | "credit-card" | "chat";

const features: { icon: FeatureIcon; title: string; description: string; link: string }[] = [
  {
    icon: "calendar",
    title: "Gym Schedule",
    description: "Check our daily workout timings and plan your sessions.",
    link: "#timings",
  },
  {
    icon: "dumbbell",
    title: "Exercise Library",
    description: "800+ exercises with videos and instructions.",
    link: "/workouts",
  },
  {
    icon: "utensils",
    title: "AI Diet Planner",
    description: "Get a personalized diet plan generated by AI.",
    link: "/fuel",
  },
  {
    icon: "calculator",
    title: "Fitness Calculators",
    description: "Calculate your BMI, TDEE, and 1 Rep Max.",
    link: "/calculators",
  },
  {
    icon: "credit-card",
    title: "Membership Pricing",
    description: "View our flexible membership plans.",
    link: "/pricing",
  },
  {
    icon: "chat",
    title: "Contact Us",
    description: "Get in touch or visit our gym.",
    link: "/contact",
  },
];

export default function FeaturesOverview() {
  return (
    <section className="surface-canvas py-16 md:py-24">
      <div className="max-w-6xl mx-auto px-4">
        {/* Header */}
        <div className="text-center mb-12" data-reveal>
          <p className="label-text text-accent mb-4">FEATURES</p>
          <h2 className="heading-display text-3xl md:text-5xl mb-6 text-hi">
            What Can You <span className="text-accent">Do</span> Here?
          </h2>
          <p className="body-text max-w-2xl mx-auto text-mid">
            Brother&apos;s Fitness is more than just a gym. We provide tools to help you
            train smarter, eat better, and track your progress, all in one place.
          </p>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 md:gap-6">
          {features.map((feature, i) => (
            <div key={feature.title} className="group h-full" data-reveal style={{ "--reveal-delay": `${i * 70}ms` } as CSSProperties}>
              <Link href={feature.link} className="block h-full">
                <div className="feature-card h-full">
                  <div className="w-12 h-12 surface-elevated hairline flex items-center justify-center mb-4 text-accent">
                    <AnimatedIcon name={feature.icon} className="w-6 h-6" label={feature.title} />
                  </div>
                  <h3 className="heading-section text-lg md:text-xl mb-2 text-hi group-hover:text-accent transition-colors duration-fast">
                    {feature.title}
                  </h3>
                  <p className="body-text text-sm text-mid">
                    {feature.description}
                  </p>
                  <p className="label-text text-accent mt-4 opacity-0 group-hover:opacity-100 transition-opacity duration-fast">
                    Explore â†’
                  </p>
                </div>
              </Link>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="text-center mt-12" data-reveal>
          <Link href="#timings">
            <div className="inline-flex items-center gap-2 surface-elevated hairline border-accent px-6 py-3">
              <AnimatedIcon name="dumbbell" className="w-5 h-5 text-accent" label="Start" />
              <span className="label-text text-hi">Start Your Transformation Today</span>
            </div>
          </Link>
        </div>
      </div>
    </section>
  );
}

